version: "3.6"
services:

  db:
    container_name: db-server
    build:
      context: ./mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - my-network
    restart: always
    tty: true

  app:
    container_name: app-server
    build:
      context: ./app
    volumes:
      - ${PROJECT_HOME}:/app
      - m2-cache:/root/.m2
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    networks:
      - my-network
    restart: always
    stdin_open: true
    tty: true

  www:
    container_name: http-server
    build:
      context: ./nginx
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - my-network
    restart: always

networks:
  my-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  m2-cache:
    driver: local
